version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: elective_disciplines
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 512m

  backend:
    build: ./backend
    container_name: fastapi_app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:PASSWORD@postgres:5432/elective_disciplines
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    mem_limit: 512m
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_web
    depends_on:
      - backend
    ports:
      - "80:80"
    mem_limit: 128m
    restart: always

volumes:
  postgres_data: