# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; during stable
# development, this is often set to date-based numbering.
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d_%%(min).2d-%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# leave blank for local time
# timezone =

# max length of characters to generate for 'slug' field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command,
# regardless of whether 'autogenerate' is used.
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# sourceless = false

# version location specification; This defaults to alembic/versions.
# When using multiple version directories, separate them with
# newlines.
# version_locations = %(here)s/bar/versions %(here)s/bat/versions

# version_path_separator = :
# set to 'true' to enable the use of .pyc files.
# sourceless = false


[post_write_hooks]
# post_write_hooks allows running scripts after a revision file is written.
# hooks are defined by providing a name and then the command to run.
# hooks are run in the order they are defined.

# example:
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
