apiVersion: v1
kind: Secret
metadata:
  name: elective-secrets
  namespace: elective
type: Opaque
stringData:
  postgres-password: "PASSWORD"
  database-url: "postgresql://postgres:PASSWORD@postgres.elective.svc.cluster.local:5432/elective_disciplines"
  secret-key: "change-me-in-production"
  google-client-id: ""
