"""add_discipline_extended_fields_v3

Revision ID: 9c58353ab292
Revises: d81c58caaf86
Create Date: 2026-04-05 14:46:49.677314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added for sqlmodel support


# revision identifiers, used by Alembic.
revision = '9c58353ab292'
down_revision = 'd81c58caaf86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discipline', sa.Column('commission_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('discipline', sa.Column('specialty_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('discipline', sa.Column('credits', sa.Float(), nullable=True))
    op.add_column('discipline', sa.Column('teacher_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('discipline', sa.Column('competence_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discipline', 'competence_type')
    op.drop_column('discipline', 'teacher_name')
    op.drop_column('discipline', 'credits')
    op.drop_column('discipline', 'specialty_code')
    op.drop_column('discipline', 'commission_name')
    # ### end Alembic commands ###
