"""Init models migration

Revision ID: d81c58caaf86
Revises: 
Create Date: 2026-03-28 14:32:34.752206

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added for sqlmodel support


# revision identifiers, used by Alembic.
revision = 'd81c58caaf86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
