"""add_picture_url_to_user

Revision ID: f1a2b3c4d5e6
Revises: 9c58353ab292
Create Date: 2026-05-05 19:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = '9c58353ab292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_url')
    # ### end Alembic commands ###
